// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBlPUhCqvzNJnRMOhYHMwRWxNiXKAcvk',
    appId: '1:93985177786:web:a8329120060b6fda30c283',
    messagingSenderId: '93985177786',
    projectId: 'flutteracademyen',
    authDomain: 'flutteracademyen.firebaseapp.com',
    storageBucket: 'flutteracademyen.appspot.com',
    measurementId: 'G-EFLQCETJGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUCoxRNOEk9oTvRTHtNTPhRg7CZojPUM',
    appId: '1:93985177786:android:fc63d941d1a9c97030c283',
    messagingSenderId: '93985177786',
    projectId: 'flutteracademyen',
    storageBucket: 'flutteracademyen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY57OxEYVEwBsjJyDYOHT4F9oyplXpktU',
    appId: '1:93985177786:ios:1b21615a0534cc5530c283',
    messagingSenderId: '93985177786',
    projectId: 'flutteracademyen',
    storageBucket: 'flutteracademyen.appspot.com',
    iosClientId: '93985177786-033t9499tkceefl3vt01pomq9vg52qf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAcademyEn',
  );
}
